ci: Debug cache paths

diff --git a/actions/install-vale/action.yml b/actions/install-vale/action.yml
--- a/actions/install-vale/action.yml
+++ b/actions/install-vale/action.yml
@@ -39,3 +39,13 @@ runs:
       if: steps.cache-vale.outputs.cache-hit != 'true'
       run: brew install vale
       shell: bash
+
+    - name: Debug cache paths
+      if: steps.cache-vale.outputs.cache-hit != 'true'
+      run: |
+        ls -la $BREW_PATH/Cellar/vale || echo "Cellar missing"
+        ls -la $BREW_PATH/bin/vale || echo "bin missing"
+        ls -la $BREW_PATH/opt/vale || echo "opt missing"
+      shell: bash
+      env:
+        BREW_PATH: ${{ steps.brew-path.outputs.prefix }}
